package com.dev.persistence.model;
// Generated 09/11/2015 04:31:59 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * OrderLine generated by hbm2java
 */
public class OrderLine implements java.io.Serializable {

	private long oliId;
	private long oliSorId;
	private long oliPrdId;
	private int oliQuantity;
	private BigDecimal oliUnitPrice;
	private BigDecimal oliTotalPrice;

	public OrderLine() {
	}

	public OrderLine(long oliId, long oliSorId, long oliPrdId, int oliQuantity, BigDecimal oliUnitPrice,
			BigDecimal oliTotalPrice) {
		this.oliId = oliId;
		this.oliSorId = oliSorId;
		this.oliPrdId = oliPrdId;
		this.oliQuantity = oliQuantity;
		this.oliUnitPrice = oliUnitPrice;
		this.oliTotalPrice = oliTotalPrice;
	}

	public long getOliId() {
		return this.oliId;
	}

	public void setOliId(long oliId) {
		this.oliId = oliId;
	}

	public long getOliSorId() {
		return this.oliSorId;
	}

	public void setOliSorId(long oliSorId) {
		this.oliSorId = oliSorId;
	}

	public long getOliPrdId() {
		return this.oliPrdId;
	}

	public void setOliPrdId(long oliPrdId) {
		this.oliPrdId = oliPrdId;
	}

	public int getOliQuantity() {
		return this.oliQuantity;
	}

	public void setOliQuantity(int oliQuantity) {
		this.oliQuantity = oliQuantity;
	}

	public BigDecimal getOliUnitPrice() {
		return this.oliUnitPrice;
	}

	public void setOliUnitPrice(BigDecimal oliUnitPrice) {
		this.oliUnitPrice = oliUnitPrice;
	}

	public BigDecimal getOliTotalPrice() {
		return this.oliTotalPrice;
	}

	public void setOliTotalPrice(BigDecimal oliTotalPrice) {
		this.oliTotalPrice = oliTotalPrice;
	}

}
