package com.dev.persistence.model;
// Generated 09/11/2015 04:31:59 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	private static final long serialVersionUID = -5672410129210199803L;
	
	private long prdId;
	private String prdCode;
	private String prdDescription;
	private int prdQuantity;
	private BigDecimal prdPrice;

	public Product() {
	}

	public Product(long prdId, String prdCode, String prdDescription, int prdQuantity, BigDecimal prdPrice) {
		this.prdId = prdId;
		this.prdCode = prdCode;
		this.prdDescription = prdDescription;
		this.prdQuantity = prdQuantity;
		this.prdPrice = prdPrice;
	}

	public long getPrdId() {
		return this.prdId;
	}

	public void setPrdId(long prdId) {
		this.prdId = prdId;
	}

	public String getPrdCode() {
		return this.prdCode;
	}

	public void setPrdCode(String prdCode) {
		this.prdCode = prdCode;
	}

	public String getPrdDescription() {
		return this.prdDescription;
	}

	public void setPrdDescription(String prdDescription) {
		this.prdDescription = prdDescription;
	}

	public int getPrdQuantity() {
		return this.prdQuantity;
	}

	public void setPrdQuantity(int prdQuantity) {
		this.prdQuantity = prdQuantity;
	}

	public BigDecimal getPrdPrice() {
		return this.prdPrice;
	}

	public void setPrdPrice(BigDecimal prdPrice) {
		this.prdPrice = prdPrice;
	}

}
