package com.dev.persistence.model;
// Generated 09/11/2015 04:31:59 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;

/**
 * SalesOrder generated by hbm2java
 */
public class SalesOrder implements java.io.Serializable {

	private long sorId;
	private String sorOrderNum;
	private long sorCusId;
	private BigDecimal sorTotalPrice;

	public SalesOrder() {
	}

	public SalesOrder(long sorId, String sorOrderNum, long sorCusId, BigDecimal sorTotalPrice) {
		this.sorId = sorId;
		this.sorOrderNum = sorOrderNum;
		this.sorCusId = sorCusId;
		this.sorTotalPrice = sorTotalPrice;
	}

	public long getSorId() {
		return this.sorId;
	}

	public void setSorId(long sorId) {
		this.sorId = sorId;
	}

	public String getSorOrderNum() {
		return this.sorOrderNum;
	}

	public void setSorOrderNum(String sorOrderNum) {
		this.sorOrderNum = sorOrderNum;
	}

	public long getSorCusId() {
		return this.sorCusId;
	}

	public void setSorCusId(long sorCusId) {
		this.sorCusId = sorCusId;
	}

	public BigDecimal getSorTotalPrice() {
		return this.sorTotalPrice;
	}

	public void setSorTotalPrice(BigDecimal sorTotalPrice) {
		this.sorTotalPrice = sorTotalPrice;
	}

}
